micronaut:
  application:
    name: pixKeymanager
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345}

jpa.default.properties.hibernate.hbm2ddl.auto: update


erp.itau.client.url: ${ERP_ITAU_CLIENT_URL:`http://localhost:9091/api/v1`}
bcb.client.url: ${BCB_CLIENT_URL:`http://localhost:8082/api/v1`}