micronaut:
  application:
    name: pixKeymanager
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345}

jpa.default.properties.hibernate.hbm2ddl.auto: update

micronaut.server.port: ${MICRONAUT_SERVER_PORT:8081}

endpoints:
  all:
    port: ${HTTP_PORT:8085}
    sensitive: ${HTTP_SENSITIVE:true}
  health:
    enabled: ${HEALTH_ENABLED:true}
    sensitive: ${HEALTH_SENSITIVE:false}
    details-visible: ${HEALTH_DETAILS_VISIBLE:ANONYMOUS}

erp.itau.client.url: ${ERP_ITAU_CLIENT_URL:`http://localhost:9091/api/v1`}
bcb.client.url: ${BCB_CLIENT_URL:`http://localhost:8082/api/v1`}