micronaut:
  application:
    name: pixKeymanager
datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    dialect: ${DB_DIALECT:POSTGRES}

jpa.default.properties.hibernate.hbm2ddl.auto: ${JPA_DLL_AUTO:update}

micronaut.server.port: ${MICRONAUT_SERVER_PORT:8081}

endpoints:
  all:
    sensitive: ${HTTP_SENSITIVE:true}
  health:
    enabled: ${HEALTH_ENABLED:true}
    sensitive: ${HEALTH_SENSITIVE:false}
    details-visible: ${HEALTH_DETAILS_VISIBLE:ANONYMOUS}

erp.itau.client.url: ${ITAU_URL:`http://localhost:9091/api/v1`}
bcb.client.url: ${BCB_URL:`http://localhost:8082/api/v1`}
